### ISSUE TITLE
Change AlertDialog title and items text

### ISSUE THREAD

**Issue by diegoaces** [aminography/ChoosePhotoHelper#1]
Hello, I would like to have the possibility to change title and items text on AlertDialog, thanks
![image](https://user-images.githubusercontent.com/45692265/62059902-21df6000-b1f2-11e9-83b7-5c9ce3e0de8e.png)

**Comment by aminography** [comment]
You should define some strings in your project's `strings.xml` with equal name defined in the library's `strings.xml`, to override them.
(Please take a look at: https://github.com/aminography/ChoosePhotoHelper/blob/master/library/src/main/res/values/strings.xml)

**Comment by diegoaces** [comment]
It works thank you

**Comment by najam-amfnrh9** [comment]
Hi dear, I have to change drawable tints colors and text color corresponds to button, how is it possible, i have used dialog themes but failing to get required result... kindly help me out
