### ISSUE TITLE
update documentation

### ISSUE THREAD

**Issue by alahammad** [aminography/ChoosePhotoHelper#12]
Hello, can you update your documentation with this : 

If you target Android 10 or higher(targetSdkVersion >= 29), set the value of requestLegacyExternalStorage to true in your app's manifest file:

<manifest ... >
    
    <application android:requestLegacyExternalStorage="true" ... >
      ...
    </application>
</manifest>

**Comment by aminography** [comment]
Hi Ala;
Yes, sure. Thanks for your contribution.

**Comment by aminography** [comment]
The problem is solved in version `1.2.0`.
