### ISSUE TITLE
Crash if one permission granted and then grant second permission when try to launch camera

### ISSUE THREAD

**Issue by Podox2** [aminography/ChoosePhotoHelper#19]
There is next code in onRequestPermissionsResult() for camera:

if ((grantResults.isNotEmpty() && grantResults[0] == PackageManager.PERMISSION_GRANTED
 && grantResults[1] == PackageManager.PERMISSION_GRANTED)) {
                        onPermissionsGranted(requestCode)
 }

But in grantResults[] will be only one object and java.lang.ArrayIndexOutOfBoundsException: length=1; index=1 will be thrown.

Simple fix is check is grantResults[] has only one object.

**Comment by aminography** [comment]
Hi @Podox2 
Thank you for reporting the issue.
I will fix it soon.
