### ISSUE TITLE
I wanted to use your chooseimage library inside a fragment can you help me with this?

### ISSUE THREAD

**Issue by Shahnwazh170** [aminography/ChoosePhotoHelper#3]

**Comment by aminography** [comment]
First of all, you can pass `getActivity()` to its builder then in `onActivityResult` and `onRequestPermissionsResult` of your `Activity`, use something like `fragment.choosePhotoHelper.onActivityResult` and `fragment.choosePhotoHelper.onRequestPermissionsResult`.
I will add fragment support in as soon as possible.

**Comment by Shahnwazh170** [comment]
Thanks for the help. I also wanted to ask you can i use this to select multiple images.

**Comment by aminography** [comment]
It now supports `Fragment`s. Enjoy it!
This library is aimed to pick a single image like profile avatar photos. It may be implemented to pick multiple images from the Gallery in the future.

**Comment by Shahnwazh170** [comment]
Okk thanks for your help.
