### ISSUE TITLE
doesn't work with AndroidX

### ISSUE THREAD

**Issue by OyaCanli** [aminography/ChoosePhotoHelper#4]
Hi! Thanks for the library, that's exactly what I needed. But it doesn't work with my project because I use androidX.
Would you consider migrating to androidX?

**Comment by aminography** [comment]
Hi; Thank you for your comment. I've tested it using AndroidX and there was no problem with it. Please share more information about what happening.

**Comment by OyaCanli** [comment]
Thanks for fast response. I had this error after adding the library: 

> Manifest merger failed with multiple errors

I have read on SO that this can occur when some dependencies use support version and some others use androidX. So I concluded that was the reason. But after your response, I double checked and found that I still keep the file provider in my manifest and your library has a file provider as well and they were colliding. The problem is solved after erasing my file provider.  So it was not because you use support, it works indeed with androidX as well. Sorry for bothering. I'm closing the issue.

**Comment by aminography** [comment]
You're welcome. Thank you for the detailed descriptions, it may happen for others.
Thanks.
