### ISSUE TITLE
Unknown URI: content://downloads/public_downloads

### ISSUE THREAD

**Issue by ahmedsalemelzeiny** [aminography/ChoosePhotoHelper#8]
I got the following issue when selecting an image from download folder 
`     Caused by: java.lang.IllegalArgumentException: Unknown URI: content://downloads/public_downloads/3054
`

**Comment by lamrak** [comment]
Also received the same error: Fatal Exception: java.lang.RuntimeException
Failure delivering result ResultInfo{who=null, request=102, result=-1, data=Intent { dat=content://com.android.providers.downloads.documents/document/61 flg=0x1 }} to activity {}: java.lang.IllegalArgumentException: Unknown URI: content://downloads/public_downloads/61

on Pixel 3

**Comment by aminography** [comment]
Thanks for reporting the issue. It has been fixed in `1.0.6` version.
