### ISSUE TITLE
Callback is not called if activity was restarted

### ISSUE THREAD

**Issue by kerleba** [aminography/ChoosePhotoHelper#9]
If caller activity gets restarted during taking photo, `cameraFilePath` is null when `onActivityResult` is called.

Steps to reproduce:

1. Turn on `Don't keep activities` setting.

2. Take photo

3. Callback gets never called because `cameraFilePath` is null.

Thanks for your work on library.

**Comment by aminography** [comment]
Thank you Klára. I'll check and fix it soon.

**Comment by kerleba** [comment]
Is there any way I can help you with this issue? I am open to help with implementation if you would prefer it.

**Comment by aminography** [comment]
Absolutely yes, please create a pull request and make the changes you want. I'd appreciate it.
